/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace Apache.Hadoop.Hbase.Thrift2
{
  public enum TDeleteType
  {
    DELETE_COLUMN = 0,
    DELETE_COLUMNS = 1,
  }
}
