/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Apache.Hadoop.Hbase.Thrift2
{

  [Serializable]
  public partial class TTimeRange : TBase
  {
    private long _minStamp;
    private long _maxStamp;

    public long MinStamp
    {
      get
      {
        return _minStamp;
      }
      set
      {
        __isset.minStamp = true;
        this._minStamp = value;
      }
    }

    public long MaxStamp
    {
      get
      {
        return _maxStamp;
      }
      set
      {
        __isset.maxStamp = true;
        this._maxStamp = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool minStamp;
      public bool maxStamp;
    }

    public TTimeRange() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              MinStamp = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I64) {
              MaxStamp = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("TTimeRange");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.minStamp) {
        field.Name = "minStamp";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(MinStamp);
        oprot.WriteFieldEnd();
      }
      if (__isset.maxStamp) {
        field.Name = "maxStamp";
        field.Type = TType.I64;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(MaxStamp);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("TTimeRange(");
      sb.Append("MinStamp: ");
      sb.Append(MinStamp);
      sb.Append(",MaxStamp: ");
      sb.Append(MaxStamp);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
