/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Apache.Hadoop.Thriftfs.Api
{

    [Serializable]
    public partial class Pathname : TBase
    {
        private string _pathname;

        public string pathname
        {
            get
            {
                return _pathname;
            }
            set
            {
                __isset.pathname = true;
                this._pathname = value;
            }
        }


        public Isset __isset;
        [Serializable]
        public struct Isset
        {
            public bool pathname;
        }

        public Pathname()
        {
        }

        public void Read(TProtocol iprot)
        {
            TField field;
            iprot.ReadStructBegin();
            while (true)
            {
                field = iprot.ReadFieldBegin();
                if (field.Type == TType.Stop)
                {
                    break;
                }
                switch (field.ID)
                {
                    case -1:
                        if (field.Type == TType.String)
                        {
                            pathname = iprot.ReadString();
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;
                    default:
                        TProtocolUtil.Skip(iprot, field.Type);
                        break;
                }
                iprot.ReadFieldEnd();
            }
            iprot.ReadStructEnd();
        }

        public void Write(TProtocol oprot)
        {
            TStruct struc = new TStruct("Pathname");
            oprot.WriteStructBegin(struc);
            TField field = new TField();
            if (pathname != null && __isset.pathname)
            {
                field.Name = "Pathname";
                field.Type = TType.String;
                field.ID = -1;
                oprot.WriteFieldBegin(field);
                oprot.WriteString(pathname);
                oprot.WriteFieldEnd();
            }
            oprot.WriteFieldStop();
            oprot.WriteStructEnd();
        }

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder("Pathname(");
            sb.Append("Pathname: ");
            sb.Append(pathname);
            sb.Append(")");
            return sb.ToString();
        }

    }

}
