/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;

namespace Apache.Hadoop.Hive
{
  public class Constants
  {
    public static string DDL_TIME = "transient_lastDdlTime";
    public static string IS_ARCHIVED = "is_archived";
    public static string ORIGINAL_LOCATION = "original_location";
    public static string META_TABLE_COLUMNS = "columns";
    public static string META_TABLE_COLUMN_TYPES = "columns.types";
    public static string BUCKET_FIELD_NAME = "bucket_field_name";
    public static string BUCKET_COUNT = "bucket_count";
    public static string FIELD_TO_DIMENSION = "field_to_dimension";
    public static string META_TABLE_NAME = "name";
    public static string META_TABLE_DB = "db";
    public static string META_TABLE_LOCATION = "location";
    public static string META_TABLE_SERDE = "serde";
    public static string META_TABLE_PARTITION_COLUMNS = "partition_columns";
    public static string FILE_INPUT_FORMAT = "file.inputformat";
    public static string FILE_OUTPUT_FORMAT = "file.outputformat";
    public static string META_TABLE_STORAGE = "storage_handler";
  }
}
