/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Apache.Hadoop.Hive
{

  [Serializable]
  public partial class PrivilegeGrantInfo : TBase
  {
    private string _privilege;
    private int _createTime;
    private string _grantor;
    private PrincipalType _grantorType;
    private bool _grantOption;

    public string Privilege
    {
      get
      {
        return _privilege;
      }
      set
      {
        __isset.privilege = true;
        this._privilege = value;
      }
    }

    public int CreateTime
    {
      get
      {
        return _createTime;
      }
      set
      {
        __isset.createTime = true;
        this._createTime = value;
      }
    }

    public string Grantor
    {
      get
      {
        return _grantor;
      }
      set
      {
        __isset.grantor = true;
        this._grantor = value;
      }
    }

    public PrincipalType GrantorType
    {
      get
      {
        return _grantorType;
      }
      set
      {
        __isset.grantorType = true;
        this._grantorType = value;
      }
    }

    public bool GrantOption
    {
      get
      {
        return _grantOption;
      }
      set
      {
        __isset.grantOption = true;
        this._grantOption = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool privilege;
      public bool createTime;
      public bool grantor;
      public bool grantorType;
      public bool grantOption;
    }

    public PrivilegeGrantInfo() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Privilege = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              CreateTime = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              Grantor = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              GrantorType = (PrincipalType)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.Bool) {
              GrantOption = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("PrivilegeGrantInfo");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Privilege != null && __isset.privilege) {
        field.Name = "privilege";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Privilege);
        oprot.WriteFieldEnd();
      }
      if (__isset.createTime) {
        field.Name = "createTime";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(CreateTime);
        oprot.WriteFieldEnd();
      }
      if (Grantor != null && __isset.grantor) {
        field.Name = "grantor";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Grantor);
        oprot.WriteFieldEnd();
      }
      if (__isset.grantorType) {
        field.Name = "grantorType";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)GrantorType);
        oprot.WriteFieldEnd();
      }
      if (__isset.grantOption) {
        field.Name = "grantOption";
        field.Type = TType.Bool;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(GrantOption);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("PrivilegeGrantInfo(");
      sb.Append("Privilege: ");
      sb.Append(Privilege);
      sb.Append(",CreateTime: ");
      sb.Append(CreateTime);
      sb.Append(",Grantor: ");
      sb.Append(Grantor);
      sb.Append(",GrantorType: ");
      sb.Append(GrantorType);
      sb.Append(",GrantOption: ");
      sb.Append(GrantOption);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
