/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Apache.Hadoop.Hive
{

  [Serializable]
  public partial class Role : TBase
  {
    private string _roleName;
    private int _createTime;
    private string _ownerName;

    public string RoleName
    {
      get
      {
        return _roleName;
      }
      set
      {
        __isset.roleName = true;
        this._roleName = value;
      }
    }

    public int CreateTime
    {
      get
      {
        return _createTime;
      }
      set
      {
        __isset.createTime = true;
        this._createTime = value;
      }
    }

    public string OwnerName
    {
      get
      {
        return _ownerName;
      }
      set
      {
        __isset.ownerName = true;
        this._ownerName = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool roleName;
      public bool createTime;
      public bool ownerName;
    }

    public Role() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              RoleName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              CreateTime = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              OwnerName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Role");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (RoleName != null && __isset.roleName) {
        field.Name = "roleName";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(RoleName);
        oprot.WriteFieldEnd();
      }
      if (__isset.createTime) {
        field.Name = "createTime";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(CreateTime);
        oprot.WriteFieldEnd();
      }
      if (OwnerName != null && __isset.ownerName) {
        field.Name = "ownerName";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(OwnerName);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Role(");
      sb.Append("RoleName: ");
      sb.Append(RoleName);
      sb.Append(",CreateTime: ");
      sb.Append(CreateTime);
      sb.Append(",OwnerName: ");
      sb.Append(OwnerName);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
