/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;

namespace Hive
{
  public class Constants
  {
    public static string SERIALIZATION_LIB = "serialization.lib";
    public static string SERIALIZATION_CLASS = "serialization.class";
    public static string SERIALIZATION_FORMAT = "serialization.format";
    public static string SERIALIZATION_DDL = "serialization.ddl";
    public static string SERIALIZATION_NULL_FORMAT = "serialization.null.format";
    public static string SERIALIZATION_LAST_COLUMN_TAKES_REST = "serialization.last.column.takes.rest";
    public static string SERIALIZATION_SORT_ORDER = "serialization.sort.order";
    public static string SERIALIZATION_USE_JSON_OBJECTS = "serialization.use.json.object";
    public static string FIELD_DELIM = "field.delim";
    public static string COLLECTION_DELIM = "colelction.delim";
    public static string LINE_DELIM = "line.delim";
    public static string MAPKEY_DELIM = "mapkey.delim";
    public static string QUOTE_CHAR = "quote.delim";
    public static string ESCAPE_CHAR = "escape.delim";
    public static string VOID_TYPE_NAME = "void";
    public static string BOOLEAN_TYPE_NAME = "boolean";
    public static string TINYINT_TYPE_NAME = "tinyint";
    public static string SMALLINT_TYPE_NAME = "smallint";
    public static string INT_TYPE_NAME = "int";
    public static string BIGINT_TYPE_NAME = "bigint";
    public static string FLOAT_TYPE_NAME = "float";
    public static string DOUBLE_TYPE_NAME = "double";
    public static string STRING_TYPE_NAME = "string";
    public static string DATE_TYPE_NAME = "date";
    public static string DATETIME_TYPE_NAME = "datetime";
    public static string TIMESTAMP_TYPE_NAME = "timestamp";
    public static string LIST_TYPE_NAME = "array";
    public static string MAP_TYPE_NAME = "map";
    public static string STRUCT_TYPE_NAME = "struct";
    public static string UNION_TYPE_NAME = "uniontype";
    public static string LIST_COLUMNS = "columns";
    public static string LIST_COLUMN_TYPES = "columns.types";
    public static THashSet<string> PrimitiveTypes = new THashSet<string>();
    public static THashSet<string> CollectionTypes = new THashSet<string>();
    static Constants()
    {
      PrimitiveTypes.Add("void");
      PrimitiveTypes.Add("boolean");
      PrimitiveTypes.Add("tinyint");
      PrimitiveTypes.Add("smallint");
      PrimitiveTypes.Add("int");
      PrimitiveTypes.Add("bigint");
      PrimitiveTypes.Add("float");
      PrimitiveTypes.Add("double");
      PrimitiveTypes.Add("string");
      PrimitiveTypes.Add("date");
      PrimitiveTypes.Add("datetime");
      PrimitiveTypes.Add("timestamp");
      CollectionTypes.Add("array");
      CollectionTypes.Add("map");
    }
  }
}
